"""empty message

Revision ID: 8050aeb59f75
Revises: 9b044763c3c2
Create Date: 2023-11-25 15:13:24.549117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8050aeb59f75'
down_revision = '9b044763c3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###
