"""empty message

Revision ID: 9aa73ef1f9ba
Revises: 8050aeb59f75
Create Date: 2023-11-26 00:10:14.834753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa73ef1f9ba'
down_revision = '8050aeb59f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('key')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration')
    # ### end Alembic commands ###
